name: CI Voll Med

on: 
  push:
    branches: ["main"]
  pull_request:
    branches:  ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Configura Docker Compose
      run: |
        sudo rm -f /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
        
    - name: Roda Docker Compose
      run: docker-compose up -d

    - name: Executa testes unitários
      run: mvn -B verify 
      
    - name: gera-relatorio-jacoco
      run: nvm jacoco:prepare-agent verify

    - name: Build and static analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: nvm sonar:sonar -Dsonar.projectKey=lucasbeninca_ci_github_aws
      
    
    
